spring.application.name: eureka-server
  #提供服务端口1111
server.port: 8762
  #提供服务的域名，这里在hosts文件中修改了
eureka.instance.hostname: peer2
  #向第二个注册中心注册自己
eureka.client.service-url.defaultZone: http://peer1:8761/eureka/