eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: zuul_book
zuul:
  routes:
#    自定义的
    api-a:
      path: /api-a/**
      serviceId: SERVICE-CLIENT
    api-b:
      path: /api-b/**
      serviceId: SERVICE-RIBBON
#  访问是的前缀
  prefix: /v1





