server:
  port: 5000
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
  application:
    name: gateway-service
zuul:
  routes:
    api-a:
      path: /user-api/**
      serviceId: user-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

